name: tests

on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.8", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set min macOS version
        if: runner.os == 'macOS'
        run: |
          echo "MACOS_DEPLOYMENT_TARGET=10.14" >> $GITHUB_ENV

      - name: Build and install
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          pip install --verbose .

      - name: Test
        run: python -m pytest
